# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='can_msg.proto',
  package='',
  serialized_pb='\n\rcan_msg.proto\"k\n\nCanMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03\x64lc\x18\x02 \x01(\x05\x12\x1f\n\x04type\x18\x03 \x01(\x0e\x32\x0c.PktTypeEnum:\x03STD\x12\x10\n\x04\x64\x61ta\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\")\n\rCanLogMessage\x12\x18\n\x03log\x18\x01 \x03(\x0b\x32\x0b.CanMessage*f\n\x0bPktTypeEnum\x12\x07\n\x03STD\x10\x00\x12\x0b\n\x07STD_RTR\x10\x01\x12\x07\n\x03\x45XT\x10\x02\x12\x0b\n\x07\x45XT_RTR\x10\x03\x12\x14\n\x10TRITIUM_SETTINGS\x10\x04\x12\x15\n\x11TRITIUM_HEARTBEAT\x10\x05')

_PKTTYPEENUM = descriptor.EnumDescriptor(
  name='PktTypeEnum',
  full_name='PktTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='STD', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STD_RTR', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXT', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXT_RTR', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRITIUM_SETTINGS', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRITIUM_HEARTBEAT', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=169,
  serialized_end=271,
)


STD = 0
STD_RTR = 1
EXT = 2
EXT_RTR = 3
TRITIUM_SETTINGS = 4
TRITIUM_HEARTBEAT = 5



_CANMESSAGE = descriptor.Descriptor(
  name='CanMessage',
  full_name='CanMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='CanMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dlc', full_name='CanMessage.dlc', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='CanMessage.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='CanMessage.data', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='CanMessage.timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=124,
)


_CANLOGMESSAGE = descriptor.Descriptor(
  name='CanLogMessage',
  full_name='CanLogMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='log', full_name='CanLogMessage.log', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=126,
  serialized_end=167,
)

_CANMESSAGE.fields_by_name['type'].enum_type = _PKTTYPEENUM
_CANLOGMESSAGE.fields_by_name['log'].message_type = _CANMESSAGE
DESCRIPTOR.message_types_by_name['CanMessage'] = _CANMESSAGE
DESCRIPTOR.message_types_by_name['CanLogMessage'] = _CANLOGMESSAGE

class CanMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CANMESSAGE
  
  # @@protoc_insertion_point(class_scope:CanMessage)

class CanLogMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CANLOGMESSAGE
  
  # @@protoc_insertion_point(class_scope:CanLogMessage)

# @@protoc_insertion_point(module_scope)
